### PR TITLE
Fix `stream::Race` to return `None` if both combined streams return `None`

### LINKED ISSUE #40: stream::Race never finishes
I'm trying to use [`stream::Race`](https://docs.rs/futures-lite/1.11.3/futures_lite/stream/struct.Race.html) to interleave a couple of timer-based streams that periodically emit events before terminating. Sadly, the current implementation of `stream::Race` will never terminate as it will always return `Poll::Pending` if no sub-stream polls `Ready(Some(_))`: https://github.com/smol-rs/futures-lite/blob/0ba0f064cc2e07190b01d15930167b62d585fa14/src/stream.rs#L2312

I'm happy to make a PR if this would be considered a bug, but I figured I'd check first since it could break users who rely on its non-termination.

### PR DESCRIPTION
**Pull request by vkrivopalov**
This makes the behavior consistent as otherwise combining two empty streams like `stream::empty::<()>.race(stream::empty())` would return `Poll::Pending`.

Fixes #40

### CODE REVIEW

File: src/stream.rs [hunk 1]
```diff
@@ -2675,8 +2702,14 @@ where
     S2: Stream<Item = T>,
 {
     Race {
-        stream1,
-        stream2,
+        stream1: Fuse {
+            stream: stream1,
+            done: false,
+        },
```
Comment (notgull) [inline src/stream.rs]: I would prefer to use the `fuse()` constructor here.

**Review by notgull — CHANGES_REQUESTED** [review]
Does this need to be done for `or()` as well?

File: src/stream.rs (hunk 1 above)
Comment (vkrivopalov) [reply src/stream.rs]: Fixed here and in other places.

**Comment by vkrivopalov** [comment]
> Does this need to be done for `or()` as well?

I guess it makes sense, I would only suggest we do this in a separate PR. This one is for the issue specifically opened for [stream::Race](https://docs.rs/futures-lite/1.11.3/futures_lite/stream/struct.Race.html) and I'd rather not mix things up.

**Review by notgull — APPROVED** [review]
Thank you!
